# Generated by Django 4.0.2 on 2023-03-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='mentors_assigned',
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
