# Generated by Django 4.0.2 on 2023-03-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_remove_mentor_module_id_remove_mentor_program_id_and_more'),
        ('sess', '0002_remove_session_mentors_assigned_alter_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='mentor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mentors.mentor'),
        ),
    ]
