# Generated by Django 4.0.2 on 2023-03-28 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('sess', '0004_remove_session_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='program',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.program'),
        ),
    ]
