# Generated by Django 4.0.2 on 2023-04-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sess', '0007_alter_session_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='module_type',
            field=models.CharField(choices=[('html_css', 'HTML/CSS'), ('python', 'Python'), ('javascript_react', 'JavaScript/React'), ('django', 'Django'), ('drf', 'DRF'), ('group', 'Group'), ('one_day_workshop', 'One Day Workshop'), ('n/a', 'Not Applicable')], max_length=255),
        ),
    ]
