# Generated by Django 4.0.2 on 2023-04-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sess', '0008_alter_session_module_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='mentors_required',
        ),
        migrations.AddField(
            model_name='session',
            name='industry_mentors_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='junior_mentors_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='lead_mentors_required',
            field=models.IntegerField(default=1),
        ),
    ]
