# Generated by Django 4.0.2 on 2023-04-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sess', '0008_alter_session_module_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.AddField(
            model_name='session',
            name='end_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='session',
            name='start_date',
            field=models.DateTimeField(default=None),
        ),
    ]
