# Generated by Django 4.0.2 on 2023-04-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sess', '0009_remove_session_mentors_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='industry_mentors_required',
        ),
        migrations.RemoveField(
            model_name='session',
            name='junior_mentors_required',
        ),
        migrations.RemoveField(
            model_name='session',
            name='lead_mentors_required',
        ),
        migrations.AddField(
            model_name='session',
            name='mentors_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='module_type',
            field=models.CharField(choices=[('html_css', 'HTML/CSS'), ('python', 'Python'), ('javascript_react', 'JavaScript/React'), ('django', 'Django'), ('drf', 'DRF'), ('group', 'Group'), ('one_day_workshop', 'One Day Workshop')], max_length=255),
        ),
    ]
