# Generated by Django 4.0.2 on 2023-04-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sess', '0010_rename_end_date_session_end_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='end_day',
            new_name='end_date',
        ),
    ]
