# Generated by Django 4.0.2 on 2023-03-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('will_travel', models.BooleanField()),
                ('junior_mentor', models.BooleanField()),
                ('industry_mentor', models.BooleanField()),
                ('lead_mentor', models.BooleanField()),
                ('she_codes_alumni', models.BooleanField()),
                ('skills', models.CharField(choices=[('html_css', 'HTML/CSS'), ('python', 'Python'), ('javascript', 'JavaScript'), ('react', 'React'), ('django', 'Django'), ('drf', 'DRF')], max_length=255)),
                ('city', models.CharField(choices=[('Brisbane', 'Brisbane'), ('Sydney', 'Sydney'), ('Perth', 'Perth')], max_length=255)),
                ('current_step', models.CharField(choices=[('step_1_interview', 'Step 1 - Interview'), ('step_2_send_offer', 'Step 2 - Send Offer'), ('step_3_send_contract', 'Step 3 - Send Contract'), ('step_4_returned_contract', 'Step 4 - Returned Contract'), ('step_5_send_calendar_invite', 'Step 5 - Send Calendar Invite'), ('step_6_onboard_mentor', 'Step 6 - Onboard Mentor'), ('step_7_mentoring', 'Step 7 - Mentoring'), ('step_8_feedback_sent', 'Step 8 - Feedback Sent'), ('step_9_offboard_mentor', 'Step 9 - Offboard Mentor')], max_length=255)),
                ('payment_type', models.CharField(choices=[('paid', 'Paid'), ('volunteer', 'Volunteer'), ('mentor_give_back', 'Mentor Give Back')], max_length=255)),
                ('notes', models.TextField()),
                ('feedback', models.TextField()),
                ('is_active', models.BooleanField()),
                ('module_id', models.IntegerField()),
                ('program_id', models.IntegerField()),
            ],
        ),
    ]
