# Generated by Django 4.0.2 on 2023-03-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentors',
            new_name='Mentor',
        ),
    ]
