# Generated by Django 4.0.2 on 2023-03-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sess', '0004_remove_session_mentor'),
        ('mentors', '0003_remove_mentor_module_id_remove_mentor_program_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sess.session'),
        ),
    ]
