# Generated by Django 4.0.2 on 2023-03-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sess', '0004_remove_session_mentor'),
        ('mentors', '0004_mentor_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='session',
        ),
        migrations.AddField(
            model_name='mentor',
            name='sessions',
            field=models.ManyToManyField(blank=True, default=None, related_name='mentors', to='sess.Session'),
        ),
    ]
