# Generated by Django 4.0.2 on 2023-03-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_remove_mentor_session_mentor_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='skills',
        ),
        migrations.AddField(
            model_name='mentor',
            name='django',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='drf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='html_css',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='javascript',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='python',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='react',
            field=models.BooleanField(default=False),
        ),
    ]
