# Generated by Django 4.0.2 on 2023-03-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sess', '0006_alter_session_program'),
        ('mentors', '0006_remove_mentor_skills_mentor_django_mentor_drf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='sess.Session'),
        ),
    ]
