# Generated by Django 4.0.2 on 2023-04-02 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentors', '0010_remove_mentornote_created_by_mentornote_noter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentornote',
            name='noter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='noter_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
