# Generated by Django 4.0.2 on 2023-04-02 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0011_alter_mentornote_noter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentornote',
            name='noter',
        ),
    ]
