# Generated by Django 4.0.2 on 2023-04-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0013_mentornote_noter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='notes',
        ),
    ]
