# Generated by Django 4.0.2 on 2023-04-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0014_remove_mentor_feedback_remove_mentor_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
