# fly.toml file generated for fully-committed-mentor-scheduling-tool on 2023-03-26T13:12:33+08:00

app = "fully-committed-mentor-scheduling-tool"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "syd"
processes = []

[env]
  PORT = "8000"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[mounts]
  source = "dbvol"
  destination = "/dbvol"