# Generated by Django 4.0.2 on 2023-03-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('city', models.CharField(choices=[('Brisbane', 'Brisbane'), ('Sydney', 'Sydney'), ('Perth', 'Perth')], max_length=50)),
                ('program_type', models.CharField(choices=[('Plus', 'Plus'), ('Flash', 'Flash'), ('Workshop', 'Workshop')], max_length=50)),
            ],
        ),
    ]
