# Generated by Django 4.0.2 on 2023-04-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(),
        ),
    ]
