# Generated by Django 4.0.2 on 2023-04-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_end_date_alter_program_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='number_of_students',
            field=models.IntegerField(default=0),
        ),
    ]
