# Generated by Django 4.0.2 on 2023-04-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_lead_mentor',
        ),
    ]
